name: run-ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-test.yml
    with:
      DOTNET_VERSION: "3.1.x"
      PROJECT_PATH: UpgradeFunction.sln